-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "moddatetime";

-- USERS Table
-- Note: Supabase provides its own 'auth.users' table. 
-- Ideally, you should link this 'public.users' table to 'auth.users' via a trigger or foreign key.
-- For now, we keep it as a standalone table or you can sync it manually.
CREATE TABLE public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password text not null, -- If using Supabase Auth, this might be redundant or store a hash from legacy
  name text not null,
  avatar text,
  location text,
  is_admin boolean default false,
  is_verified boolean default false,
  member_since int default EXTRACT(YEAR FROM CURRENT_DATE),
  response_rate text default '0%',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trigger for updated_at
CREATE TRIGGER handle_updated_at_users
BEFORE UPDATE ON public.users
FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);

-- CATEGORIES Table
CREATE TABLE public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  icon text,
  parent_id bigint references public.categories(id) on delete cascade,
  display_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TRIGGER handle_updated_at_categories
BEFORE UPDATE ON public.categories
FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);

-- PRODUCTS Table
CREATE TABLE public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  price decimal(10, 2) not null,
  currency text default 'XAF',
  image text,
  category text, -- Legacy column
  category_id bigint references public.categories(id) on delete set null,
  brand text,
  size text,
  condition_status text,
  description text,
  location text,
  seller_id bigint not null references public.users(id) on delete cascade,
  likes int default 0,
  average_rating decimal(3,2) default 0.00,
  review_count int default 0,
  posted_at timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX idx_products_category ON public.products(category);
CREATE INDEX idx_products_seller ON public.products(seller_id);
CREATE INDEX idx_products_category_id ON public.products(category_id);

CREATE TRIGGER handle_updated_at_products
BEFORE UPDATE ON public.products
FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);

-- MESSAGES Table
CREATE TABLE public.messages (
  id bigint generated by default as identity primary key,
  sender_id bigint not null references public.users(id) on delete cascade,
  receiver_id bigint not null references public.users(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  content text not null,
  attachment_url text,
  attachment_type text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX idx_messages_sender ON public.messages(sender_id);
CREATE INDEX idx_messages_receiver ON public.messages(receiver_id);

-- ORDERS Table
CREATE TABLE public.orders (
  id bigint generated by default as identity primary key,
  order_number text unique,
  buyer_id bigint not null references public.users(id),
  seller_id bigint not null references public.users(id),
  total_amount decimal(10, 2) not null,
  currency text default 'XAF',
  status text default 'pending' check (status in ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled')),
  shipping_address text,
  payment_method text default 'card',
  payment_status text default 'pending' check (payment_status in ('pending', 'completed', 'failed', 'refunded')),
  payment_id text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX idx_orders_buyer ON public.orders(buyer_id);
CREATE INDEX idx_orders_seller ON public.orders(seller_id);
CREATE INDEX idx_orders_status ON public.orders(status);
CREATE INDEX idx_orders_number ON public.orders(order_number);

CREATE TRIGGER handle_updated_at_orders
BEFORE UPDATE ON public.orders
FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);

-- ORDER ITEMS Table
CREATE TABLE public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity int not null default 1,
  unit_price decimal(10, 2) not null,
  subtotal decimal(10, 2) not null,
  product_snapshot jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX idx_order_items_order ON public.order_items(order_id);

-- WISHLISTS Table
CREATE TABLE public.wishlists (
  user_id bigint not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, product_id)
);

-- CART ITEMS Table
CREATE TABLE public.cart_items (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity int not null default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, product_id)
);

CREATE INDEX idx_cart_user ON public.cart_items(user_id);
CREATE INDEX idx_cart_product ON public.cart_items(product_id);

CREATE TRIGGER handle_updated_at_cart_items
BEFORE UPDATE ON public.cart_items
FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);

-- REVIEWS Table
CREATE TABLE public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  rating int not null check (rating >= 1 and rating <= 5),
  title text,
  comment text,
  helpful_count int default 0,
  verified_purchase boolean default false,
  is_approved boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, product_id)
);

CREATE INDEX idx_reviews_product ON public.reviews(product_id);
CREATE INDEX idx_reviews_user ON public.reviews(user_id);
CREATE INDEX idx_reviews_rating ON public.reviews(rating);

CREATE TRIGGER handle_updated_at_reviews
BEFORE UPDATE ON public.reviews
FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);

-- REVIEW HELPFUL Table
CREATE TABLE public.review_helpful (
  review_id bigint not null references public.reviews(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (review_id, user_id)
);

-- RATE LIMITS Table
CREATE TABLE public.rate_limits (
  key text primary key,
  attempts int default 0,
  reset_at timestamp with time zone
);

-------------------------------------------------------------------------------
-- SEED DATA (Categories)
-------------------------------------------------------------------------------
INSERT INTO public.categories (name, slug, icon, display_order) VALUES
('Women', 'women', 'shirt', 1),
('Men', 'men', 'user', 2),
('Kids', 'kids', 'baby', 3),
('Home & Garden', 'home', 'home', 4),
('Electronics', 'tech', 'smartphone', 5),
('Entertainment', 'ent', 'gamepad-2', 6),
('Beauty & Health', 'beauty', 'sparkles', 7),
('Vehicles', 'vehicles', 'car', 8),
('Real Estate', 'real-estate', 'building', 9),
('Sports & Outdoors', 'sports', 'dumbbell', 10)
ON CONFLICT (slug) DO NOTHING;
