-- 1. Drop Legacy Tables (Cascade will handle dependents)
DROP TABLE IF EXISTS public.users CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.cart_items CASCADE;
DROP TABLE IF EXISTS public.wishlists CASCADE;
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
-- Note: categories can stay if they don't reference users, but products reference them. 
-- We'll keep categories but let cascade clean references.

-- 2. Create PROFILES Table (Standard Supabase Pattern)
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email text,
  name text,
  avatar text,
  location text,
  is_verified boolean DEFAULT false,
  is_admin boolean DEFAULT false,
  member_since int DEFAULT EXTRACT(YEAR FROM CURRENT_DATE),
  response_rate text DEFAULT '100%',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Trigger for profiles
CREATE TRIGGER handle_updated_at_profiles
BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);

-- RLS for Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 3. Re-create PRODUCTS Table (with UUID)
CREATE TABLE public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  price decimal(10, 2) not null,
  currency text default 'XAF',
  image text,
  category_id bigint references public.categories(id) on delete set null,
  brand text,
  size text,
  condition_status text,
  description text,
  location text,
  seller_id uuid not null references public.profiles(id) on delete cascade, -- UUID
  likes int default 0,
  average_rating decimal(3,2) default 0.00,
  review_count int default 0,
  posted_at timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Triggers/Indexes
CREATE TRIGGER handle_updated_at_products BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Products are viewable by everyone" ON public.products FOR SELECT USING (true);
CREATE POLICY "Users can insert own products" ON public.products FOR INSERT WITH CHECK (auth.uid() = seller_id);
-- simplified policies for dev

-- 4. Re-create CART ITEMS Table (with UUID)
CREATE TABLE public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade, -- UUID
  product_id bigint not null references public.products(id) on delete cascade,
  quantity int not null default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, product_id)
);
CREATE TRIGGER handle_updated_at_cart_items BEFORE UPDATE ON public.cart_items FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can see own cart" ON public.cart_items FOR ALL USING (auth.uid() = user_id);

-- 5. Re-create ORDERS Table (with UUID)
CREATE TABLE public.orders (
  id bigint generated by default as identity primary key,
  order_number text unique,
  buyer_id uuid not null references public.profiles(id), -- UUID
  seller_id uuid not null references public.profiles(id), -- UUID
  total_amount decimal(10, 2) not null,
  currency text default 'XAF',
  status text default 'pending',
  shipping_address text,
  payment_method text default 'card',
  payment_status text default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
CREATE TRIGGER handle_updated_at_orders BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can see own orders" ON public.orders FOR ALL USING (auth.uid() = buyer_id OR auth.uid() = seller_id);

-- 6. ORDER ITEMS (Dependent on Orders, standard)
CREATE TABLE public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity int not null default 1,
  unit_price decimal(10, 2) not null,
  subtotal decimal(10, 2) not null,
  product_snapshot jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can see own order items" ON public.order_items FOR ALL USING (
  exists (select 1 from public.orders where id = order_items.order_id and (buyer_id = auth.uid() or seller_id = auth.uid()))
);

-- 7. REVIEWS (with UUID)
CREATE TABLE public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade, -- UUID
  rating int not null check (rating >= 1 and rating <= 5),
  title text,
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Reviews are public" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Users can create reviews" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 8. WISHLISTS (with UUID)
CREATE TABLE public.wishlists (
  user_id uuid not null references public.profiles(id) on delete cascade, -- UUID
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, product_id)
);
ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage own wishlist" ON public.wishlists FOR ALL USING (auth.uid() = user_id);

-- 9. NOTIFICATIONS (already UUID, but ensure link)
-- Assuming notifications table was created in previous step with UUID, it should be fine.
-- If we dropped CASCADE users, notifications might be gone if they referenced public.users.
-- Let's ensure notifications exists and uses UUID.
CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  type text,
  title text,
  message text,
  link text,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can see own notifications" ON public.notifications FOR ALL USING (auth.uid() = user_id);


-- 10. Auto-Profile Creation Trigger (Crucial!)
-- Automatically create a profile when a user signs up.
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name, avatar)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if exists
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
ALTER PUBLICATION supabase_realtime ADD TABLE public.profiles;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
