-- PROFESSIONAL v2 SCHEMA MIGRATION

-- 1. STORES (Multi-Vendor)
-- Separates the "Shop" entity from the "User" entity.
CREATE TABLE public.stores (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  owner_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  slug text UNIQUE NOT NULL,
  name text NOT NULL,
  description text,
  logo_url text, -- Storage: store-branding
  cover_url text, -- Storage: store-branding
  is_verified boolean DEFAULT false,
  rating decimal(3,2) DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER handle_updated_at_stores BEFORE UPDATE ON public.stores FOR EACH ROW EXECUTE PROCEDURE moddatetime (updated_at);

-- 2. ADDRESSES (Address Book)
-- Allows users to save multiple shipping/billing locations.
CREATE TABLE public.addresses (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  label text, -- e.g. "Home", "Office"
  recipient_name text NOT NULL,
  phone_number text,
  address_line1 text NOT NULL,
  address_line2 text,
  city text NOT NULL,
  state text, -- Department/Region in Congo
  postal_code text,
  country text DEFAULT 'Congo',
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. PRODUCT VARIANTS (SKU Management)
-- Handles sizes, colors, and stock levels granularly.
CREATE TABLE public.product_variants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  sku text,
  attributes jsonb DEFAULT '{}', -- e.g. {"size": "42", "color": "red"}
  price_adjustment decimal(10, 2) DEFAULT 0.00,
  stock_quantity int DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TRANSACTIONS (Financial Ledger)
-- Immutable record of money movement.
CREATE TABLE public.transactions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  reference text UNIQUE NOT NULL, -- Flutterwave Ref
  user_id uuid REFERENCES public.profiles(id),
  store_id uuid REFERENCES public.stores(id),
  type text NOT NULL, -- 'payment', 'payout', 'refund'
  provider text DEFAULT 'flutterwave',
  status text DEFAULT 'pending', -- 'success', 'failed'
  amount decimal(15, 2) NOT NULL,
  currency text DEFAULT 'XAF',
  metadata jsonb DEFAULT '{}',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. KYC (Verification)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS kyc_status text DEFAULT 'unverified'; -- 'pending', 'verified', 'rejected'
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS kyc_docs_url text[]; -- Array of private storage paths

-- RLS POLICIES
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public stores read" ON public.stores FOR SELECT USING (true);
CREATE POLICY "Owners manage stores" ON public.stores FOR ALL USING (auth.uid() = owner_id);

ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage addresses" ON public.addresses FOR ALL USING (auth.uid() = user_id);

ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users view own tx" ON public.transactions FOR SELECT USING (auth.uid() = user_id);
-- Only system can insert transactions (service role)

-- Link Products to Stores (Transition)
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS store_id uuid REFERENCES public.stores(id) ON DELETE SET NULL;
